"""empty message

Revision ID: 535818ce8da0
Revises: 
Create Date: 2018-06-20 20:48:45.647207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535818ce8da0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('congress_twitter', sa.Column('topic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('congress_twitter', 'topic')
    # ### end Alembic commands ###
